version: '2'
services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: 'false'
    networks:
      - zephyr-network
# TOOD -> Volumes so config files work lol
  zephyr:
    container_name: zephyr
    build:
      dockerfile: Dockerfile
    image: zephyr:latest
    ports:
      - 8080:8080
    networks:
      - zephyr-network
    volumes:
      - ./config:/Zephyr/config
networks:
  zephyr-network:
    driver: bridge

volumes:
  zephyr-data: