name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # chmod the gradle file before running as sometimes actions do not have permission
      - name: Enable Gradle permissions
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Run scan
        run: ./gradlew build --scan