name: build-and-test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    needs: build  # Ensure 'build' job completes before running this job

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Set up Gradle
        uses: gradle/setup-gradle@v4
        with:
          gradle-version: 7.3

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test --stacktrace
